version: '3.4'

services:
  basicdeploydigitalocean:
    image: basicdeploydigitalocean
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file:
    - ./.env
    ports:
    - target: ${PORT}
      published: ${PORT_EXPOSE}
      protocol: tcp
      mode: host